### ISSUE TITLE
Needed with 2.0.2?

### ISSUE THREAD

**Issue by ronlut** [atombender/sublime_text_alternative_autocompletion#24]
Hi.
Using sublime's default auto-complete (tab key and the popup), it produces pretty much the same behavior as described in the readme file of this repo.
Am I missing something?
Thanks a lot!

**Comment by atombender** [comment]
Sublime's default autocomplete shows a popup, this doesn't. Last I checked, it didn't cycle the selection like this plugin does.

**Comment by ronlut** [comment]
Thanks for the quick reply.
I hope you understand I didn't mean to disrespect your work or something, just asking as I'm really new to sublime.
I just checked with ST 2.0.2 without the alternative_autocompletion plugin, and pressing tab more than once cycles through the selection.
Again, i'm pretty new so maybe my check isn't valid.
What I did is close Sublime, delete the alternative_autocompletion from the Plugins folder and restart Sublime.

**Comment by atombender** [comment]
No worries. So you mean the tab completion, which doesn't use a popup. Well, there are some small but important differences.
- ST cannot cycle backwards (there is no shift-tab).
- If you move the cursor, it loses completion state.
- ST is also a lot looser about what it considers a match. For example, if you type `exe`, it will complete that to `execute` but also to `extension`, which my plugin won't.

By the way, you should be using [Package Control](https://sublime.wbond.net) to install and uninstall packages, rather than working on the plugins folder manually.

**Comment by ronlut** [comment]
Thanks a lot for the clarification.
Now I know why I do want your plugin! :relieved:

**Comment by zengabor** [comment]
Just for the record, this is my favorite plugin for Sublime Text. :)

**Comment by atombender** [comment]
Thanks, guys!

**Comment by ccampbell** [comment]
Yeah, if it weren't for this plugin I wouldn't have been able to switch away from TextMate.  It still baffles me how people use Sublime with the default autocomplete.  

I did a write up about it here before I discovered this extension:
http://www.sublimetext.com/forum/viewtopic.php?f=3&t=5711

**Comment by zengabor** [comment]
Just curious: why did you switch away from TextMate?
